// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreAnimation;
using Foundation;
using UIKit;

namespace WeatherApp.iOS
{
    public partial class RotatingImageView : UIImageView
	{
        bool isRotating;

		public RotatingImageView (IntPtr handle) : base (handle)
		{
		}

        public bool IsRotating
        {
            get
            {
                return isRotating;
            }

            set
            {
                if (value != isRotating)
                {
                    isRotating = value;
                    SetAnimation(value);
                }

            }
        }

        void Spin()
        {
            if (!IsRotating) return;
            if (Layer.AnimationForKey("Rotation") != null) return;

            var animation = new CABasicAnimation();
            animation.KeyPath = "transform.rotation.z";
            animation.To = NSNumber.FromDouble(Math.PI * 2);
            animation.Duration = 2.0;
            animation.Cumulative = true;
            animation.RepeatCount = 1;
            animation.AnimationStopped += (s, a) => Spin();

            Layer.AddAnimation(animation, "Rotation");
        }

        void SetAnimation(bool animating)
        {
            if (animating)
            {
                Spin();
            }
        }
    }
}
