#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WeatherApp.Droid.Resource", IsApplication=true)]

namespace WeatherApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int image_rotate = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int linear_interpolator = 2131034113;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int constraintSet = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int fastScrollEnabled = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int fastScrollHorizontalThumbDrawable = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fastScrollHorizontalTrackDrawable = 2130771976;
			
			// aapt resource value: 0x7f010005
			public const int fastScrollVerticalThumbDrawable = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int fastScrollVerticalTrackDrawable = 2130771974;
			
			// aapt resource value: 0x7f01003c
			public const int font = 2130772028;
			
			// aapt resource value: 0x7f010035
			public const int fontProviderAuthority = 2130772021;
			
			// aapt resource value: 0x7f010038
			public const int fontProviderCerts = 2130772024;
			
			// aapt resource value: 0x7f010039
			public const int fontProviderFetchStrategy = 2130772025;
			
			// aapt resource value: 0x7f01003a
			public const int fontProviderFetchTimeout = 2130772026;
			
			// aapt resource value: 0x7f010036
			public const int fontProviderPackage = 2130772022;
			
			// aapt resource value: 0x7f010037
			public const int fontProviderQuery = 2130772023;
			
			// aapt resource value: 0x7f01003b
			public const int fontStyle = 2130772027;
			
			// aapt resource value: 0x7f01003d
			public const int fontWeight = 2130772029;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f01000a
			public const int layout_constraintBaseline_creator = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int layout_constraintBaseline_toBaselineOf = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int layout_constraintBottom_creator = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int layout_constraintBottom_toBottomOf = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int layout_constraintBottom_toTopOf = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int layout_constraintDimensionRatio = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int layout_constraintEnd_toEndOf = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int layout_constraintEnd_toStartOf = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int layout_constraintGuide_begin = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int layout_constraintGuide_end = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int layout_constraintGuide_percent = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int layout_constraintHeight_default = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int layout_constraintHeight_max = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int layout_constraintHeight_min = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int layout_constraintHorizontal_bias = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int layout_constraintHorizontal_chainStyle = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int layout_constraintHorizontal_weight = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int layout_constraintLeft_creator = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int layout_constraintLeft_toLeftOf = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int layout_constraintLeft_toRightOf = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int layout_constraintRight_creator = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int layout_constraintRight_toLeftOf = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int layout_constraintRight_toRightOf = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int layout_constraintStart_toEndOf = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int layout_constraintStart_toStartOf = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int layout_constraintTop_creator = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int layout_constraintTop_toBottomOf = 2130772004;
			
			// aapt resource value: 0x7f010025
			public const int layout_constraintTop_toTopOf = 2130772005;
			
			// aapt resource value: 0x7f010026
			public const int layout_constraintVertical_bias = 2130772006;
			
			// aapt resource value: 0x7f010027
			public const int layout_constraintVertical_chainStyle = 2130772007;
			
			// aapt resource value: 0x7f010028
			public const int layout_constraintVertical_weight = 2130772008;
			
			// aapt resource value: 0x7f010029
			public const int layout_constraintWidth_default = 2130772009;
			
			// aapt resource value: 0x7f01002a
			public const int layout_constraintWidth_max = 2130772010;
			
			// aapt resource value: 0x7f01002b
			public const int layout_constraintWidth_min = 2130772011;
			
			// aapt resource value: 0x7f01002c
			public const int layout_editor_absoluteX = 2130772012;
			
			// aapt resource value: 0x7f01002d
			public const int layout_editor_absoluteY = 2130772013;
			
			// aapt resource value: 0x7f01002e
			public const int layout_goneMarginBottom = 2130772014;
			
			// aapt resource value: 0x7f01002f
			public const int layout_goneMarginEnd = 2130772015;
			
			// aapt resource value: 0x7f010030
			public const int layout_goneMarginLeft = 2130772016;
			
			// aapt resource value: 0x7f010031
			public const int layout_goneMarginRight = 2130772017;
			
			// aapt resource value: 0x7f010032
			public const int layout_goneMarginStart = 2130772018;
			
			// aapt resource value: 0x7f010033
			public const int layout_goneMarginTop = 2130772019;
			
			// aapt resource value: 0x7f010034
			public const int layout_optimizationLevel = 2130772020;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0c0000
			public const int abc_action_bar_embed_tabs = 2131492864;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090003
			public const int notification_action_color_filter = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int notification_icon_bg_color = 2131296260;
			
			// aapt resource value: 0x7f090000
			public const int notification_material_background_media_default_color = 2131296256;
			
			// aapt resource value: 0x7f090007
			public const int orange = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int orange_dark = 2131296264;
			
			// aapt resource value: 0x7f090001
			public const int primary_text_default_material_dark = 2131296257;
			
			// aapt resource value: 0x7f090005
			public const int ripple_material_light = 2131296261;
			
			// aapt resource value: 0x7f090002
			public const int secondary_text_default_material_dark = 2131296258;
			
			// aapt resource value: 0x7f090006
			public const int secondary_text_default_material_light = 2131296262;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f06000a
			public const int compat_button_inset_horizontal_material = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int compat_button_inset_vertical_material = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int compat_button_padding_horizontal_material = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int compat_button_padding_vertical_material = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int compat_control_corner_material = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int fastscroll_default_thickness = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int fastscroll_margin = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int fastscroll_minimum_range = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int item_touch_helper_swipe_escape_max_velocity = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int item_touch_helper_swipe_escape_velocity = 2131099653;
			
			// aapt resource value: 0x7f06000f
			public const int notification_action_icon_size = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int notification_action_text_size = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int notification_big_circle_margin = 2131099665;
			
			// aapt resource value: 0x7f060007
			public const int notification_content_margin_start = 2131099655;
			
			// aapt resource value: 0x7f060012
			public const int notification_large_icon_height = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int notification_large_icon_width = 2131099667;
			
			// aapt resource value: 0x7f060008
			public const int notification_main_column_padding_top = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int notification_media_narrow_margin = 2131099657;
			
			// aapt resource value: 0x7f060014
			public const int notification_right_icon_size = 2131099668;
			
			// aapt resource value: 0x7f060006
			public const int notification_right_side_padding_top = 2131099654;
			
			// aapt resource value: 0x7f060015
			public const int notification_small_icon_background_padding = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int notification_small_icon_size_as_large = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int notification_subtext_size = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int notification_top_pad = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int notification_top_pad_large_text = 2131099673;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_shape = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int @checked = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int et_shape = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int fav_selector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_star_black_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_star_border_black_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_sun = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_action_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notification_bg_low = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int notification_bg_low_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notification_bg_low_pressed = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int notification_bg_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int notification_bg_normal_pressed = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int notification_icon_background = 2130837518;
			
			// aapt resource value: 0x7f020012
			public const int notification_template_icon_bg = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int notification_template_icon_low_bg = 2130837523;
			
			// aapt resource value: 0x7f02000f
			public const int notification_tile_bg = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int notify_panel_notification_icon_bg = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int splash_screen = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070028
			public const int action0 = 2131165224;
			
			// aapt resource value: 0x7f070025
			public const int action_container = 2131165221;
			
			// aapt resource value: 0x7f07002c
			public const int action_divider = 2131165228;
			
			// aapt resource value: 0x7f070026
			public const int action_image = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int action_text = 2131165223;
			
			// aapt resource value: 0x7f070035
			public const int actions = 2131165237;
			
			// aapt resource value: 0x7f07000c
			public const int all = 2131165196;
			
			// aapt resource value: 0x7f070010
			public const int async = 2131165200;
			
			// aapt resource value: 0x7f07000d
			public const int basic = 2131165197;
			
			// aapt resource value: 0x7f070011
			public const int blocking = 2131165201;
			
			// aapt resource value: 0x7f070022
			public const int btnSearch = 2131165218;
			
			// aapt resource value: 0x7f070029
			public const int cancel_action = 2131165225;
			
			// aapt resource value: 0x7f07000e
			public const int chains = 2131165198;
			
			// aapt resource value: 0x7f070031
			public const int chronometer = 2131165233;
			
			// aapt resource value: 0x7f070037
			public const int end_padder = 2131165239;
			
			// aapt resource value: 0x7f070021
			public const int etCitySearch = 2131165217;
			
			// aapt resource value: 0x7f070012
			public const int forever = 2131165202;
			
			// aapt resource value: 0x7f070018
			public const int icon = 2131165208;
			
			// aapt resource value: 0x7f070036
			public const int icon_group = 2131165238;
			
			// aapt resource value: 0x7f070032
			public const int info = 2131165234;
			
			// aapt resource value: 0x7f070013
			public const int italic = 2131165203;
			
			// aapt resource value: 0x7f070000
			public const int item_touch_helper_previous_elevation = 2131165184;
			
			// aapt resource value: 0x7f070020
			public const int ivIcon = 2131165216;
			
			// aapt resource value: 0x7f07001b
			public const int ivWeatherIcon = 2131165211;
			
			// aapt resource value: 0x7f070001
			public const int line1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int line3 = 2131165186;
			
			// aapt resource value: 0x7f07002b
			public const int media_actions = 2131165227;
			
			// aapt resource value: 0x7f07000f
			public const int none = 2131165199;
			
			// aapt resource value: 0x7f070014
			public const int normal = 2131165204;
			
			// aapt resource value: 0x7f070034
			public const int notification_background = 2131165236;
			
			// aapt resource value: 0x7f07002e
			public const int notification_main_column = 2131165230;
			
			// aapt resource value: 0x7f07002d
			public const int notification_main_column_container = 2131165229;
			
			// aapt resource value: 0x7f07000a
			public const int packed = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int parent = 2131165191;
			
			// aapt resource value: 0x7f07001f
			public const int recyclerDily = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int recyclerHourly = 2131165214;
			
			// aapt resource value: 0x7f070033
			public const int right_icon = 2131165235;
			
			// aapt resource value: 0x7f07002f
			public const int right_side = 2131165231;
			
			// aapt resource value: 0x7f070008
			public const int spread = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int spread_inside = 2131165195;
			
			// aapt resource value: 0x7f07002a
			public const int status_bar_latest_event_content = 2131165226;
			
			// aapt resource value: 0x7f070003
			public const int tag_transition_group = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int text = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int text2 = 2131165189;
			
			// aapt resource value: 0x7f070030
			public const int time = 2131165232;
			
			// aapt resource value: 0x7f070006
			public const int title = 2131165190;
			
			// aapt resource value: 0x7f070019
			public const int toolbar = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int tvCityName = 2131165210;
			
			// aapt resource value: 0x7f070015
			public const int tvDay = 2131165205;
			
			// aapt resource value: 0x7f070023
			public const int tvHour = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int tvTemp = 2131165220;
			
			// aapt resource value: 0x7f070017
			public const int tvTempDay = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int tvTempNight = 2131165206;
			
			// aapt resource value: 0x7f07001d
			public const int tvTodayName = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int tvWeatherTemp = 2131165212;
			
			// aapt resource value: 0x7f070009
			public const int wrap = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int cancel_button_image_alpha = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int status_bar_notification_info_maxnum = 2131361793;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int DailyWeatherAdapter = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int DetailsPage = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int HomePage = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int HourlyWeatherAdapter = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_action = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_action_tombstone = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_media_action = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int notification_media_cancel_action = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int notification_template_big_media = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int notification_template_big_media_custom = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int notification_template_big_media_narrow = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int notification_template_big_media_narrow_custom = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int notification_template_custom_big = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int notification_template_icon_group = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int notification_template_lines_media = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int notification_template_media = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int notification_template_media_custom = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int notification_template_part_chronometer = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int notification_template_part_time = 2130968594;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0b0002
			public const int app_name = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int celsius = 2131427331;
			
			// aapt resource value: 0x7f0b0001
			public const int hello = 2131427329;
			
			// aapt resource value: 0x7f0b0000
			public const int status_bar_notification_info_overflow = 2131427328;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f08000c
			public const int SplashScreen = 2131230732;
			
			// aapt resource value: 0x7f080005
			public const int TextAppearance_Compat_Notification = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int TextAppearance_Compat_Notification_Info = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131230731;
			
			// aapt resource value: 0x7f080004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int TextAppearance_Compat_Notification_Media = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int TextAppearance_Compat_Notification_Time = 2131230727;
			
			// aapt resource value: 0x7f080002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131230722;
			
			// aapt resource value: 0x7f080008
			public const int TextAppearance_Compat_Notification_Title = 2131230728;
			
			// aapt resource value: 0x7f080003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131230723;
			
			// aapt resource value: 0x7f080009
			public const int Widget_Compat_NotificationActionContainer = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int Widget_Compat_NotificationActionText = 2131230730;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ConstraintLayout_Layout = new int[] {
					16842948,
					16843039,
					16843040,
					16843071,
					16843072,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020};
			
			// aapt resource value: 2
			public const int ConstraintLayout_Layout_android_maxHeight = 2;
			
			// aapt resource value: 1
			public const int ConstraintLayout_Layout_android_maxWidth = 1;
			
			// aapt resource value: 4
			public const int ConstraintLayout_Layout_android_minHeight = 4;
			
			// aapt resource value: 3
			public const int ConstraintLayout_Layout_android_minWidth = 3;
			
			// aapt resource value: 0
			public const int ConstraintLayout_Layout_android_orientation = 0;
			
			// aapt resource value: 5
			public const int ConstraintLayout_Layout_constraintSet = 5;
			
			// aapt resource value: 6
			public const int ConstraintLayout_Layout_layout_constraintBaseline_creator = 6;
			
			// aapt resource value: 7
			public const int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 7;
			
			// aapt resource value: 8
			public const int ConstraintLayout_Layout_layout_constraintBottom_creator = 8;
			
			// aapt resource value: 9
			public const int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 9;
			
			// aapt resource value: 10
			public const int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 10;
			
			// aapt resource value: 11
			public const int ConstraintLayout_Layout_layout_constraintDimensionRatio = 11;
			
			// aapt resource value: 12
			public const int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 12;
			
			// aapt resource value: 13
			public const int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 13;
			
			// aapt resource value: 14
			public const int ConstraintLayout_Layout_layout_constraintGuide_begin = 14;
			
			// aapt resource value: 15
			public const int ConstraintLayout_Layout_layout_constraintGuide_end = 15;
			
			// aapt resource value: 16
			public const int ConstraintLayout_Layout_layout_constraintGuide_percent = 16;
			
			// aapt resource value: 17
			public const int ConstraintLayout_Layout_layout_constraintHeight_default = 17;
			
			// aapt resource value: 18
			public const int ConstraintLayout_Layout_layout_constraintHeight_max = 18;
			
			// aapt resource value: 19
			public const int ConstraintLayout_Layout_layout_constraintHeight_min = 19;
			
			// aapt resource value: 20
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 20;
			
			// aapt resource value: 21
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 21;
			
			// aapt resource value: 22
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 22;
			
			// aapt resource value: 23
			public const int ConstraintLayout_Layout_layout_constraintLeft_creator = 23;
			
			// aapt resource value: 24
			public const int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 24;
			
			// aapt resource value: 25
			public const int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 25;
			
			// aapt resource value: 26
			public const int ConstraintLayout_Layout_layout_constraintRight_creator = 26;
			
			// aapt resource value: 27
			public const int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 27;
			
			// aapt resource value: 28
			public const int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 28;
			
			// aapt resource value: 29
			public const int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 29;
			
			// aapt resource value: 30
			public const int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 30;
			
			// aapt resource value: 31
			public const int ConstraintLayout_Layout_layout_constraintTop_creator = 31;
			
			// aapt resource value: 32
			public const int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 32;
			
			// aapt resource value: 33
			public const int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 33;
			
			// aapt resource value: 34
			public const int ConstraintLayout_Layout_layout_constraintVertical_bias = 34;
			
			// aapt resource value: 35
			public const int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 35;
			
			// aapt resource value: 36
			public const int ConstraintLayout_Layout_layout_constraintVertical_weight = 36;
			
			// aapt resource value: 37
			public const int ConstraintLayout_Layout_layout_constraintWidth_default = 37;
			
			// aapt resource value: 38
			public const int ConstraintLayout_Layout_layout_constraintWidth_max = 38;
			
			// aapt resource value: 39
			public const int ConstraintLayout_Layout_layout_constraintWidth_min = 39;
			
			// aapt resource value: 40
			public const int ConstraintLayout_Layout_layout_editor_absoluteX = 40;
			
			// aapt resource value: 41
			public const int ConstraintLayout_Layout_layout_editor_absoluteY = 41;
			
			// aapt resource value: 42
			public const int ConstraintLayout_Layout_layout_goneMarginBottom = 42;
			
			// aapt resource value: 43
			public const int ConstraintLayout_Layout_layout_goneMarginEnd = 43;
			
			// aapt resource value: 44
			public const int ConstraintLayout_Layout_layout_goneMarginLeft = 44;
			
			// aapt resource value: 45
			public const int ConstraintLayout_Layout_layout_goneMarginRight = 45;
			
			// aapt resource value: 46
			public const int ConstraintLayout_Layout_layout_goneMarginStart = 46;
			
			// aapt resource value: 47
			public const int ConstraintLayout_Layout_layout_goneMarginTop = 47;
			
			// aapt resource value: 48
			public const int ConstraintLayout_Layout_layout_optimizationLevel = 48;
			
			public static int[] ConstraintSet = new int[] {
					16842948,
					16842960,
					16842972,
					16842996,
					16842997,
					16842999,
					16843000,
					16843001,
					16843002,
					16843551,
					16843552,
					16843553,
					16843554,
					16843555,
					16843556,
					16843557,
					16843559,
					16843560,
					16843701,
					16843702,
					16843770,
					16843840,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019};
			
			// aapt resource value: 9
			public const int ConstraintSet_android_alpha = 9;
			
			// aapt resource value: 21
			public const int ConstraintSet_android_elevation = 21;
			
			// aapt resource value: 1
			public const int ConstraintSet_android_id = 1;
			
			// aapt resource value: 4
			public const int ConstraintSet_android_layout_height = 4;
			
			// aapt resource value: 8
			public const int ConstraintSet_android_layout_marginBottom = 8;
			
			// aapt resource value: 19
			public const int ConstraintSet_android_layout_marginEnd = 19;
			
			// aapt resource value: 5
			public const int ConstraintSet_android_layout_marginLeft = 5;
			
			// aapt resource value: 7
			public const int ConstraintSet_android_layout_marginRight = 7;
			
			// aapt resource value: 18
			public const int ConstraintSet_android_layout_marginStart = 18;
			
			// aapt resource value: 6
			public const int ConstraintSet_android_layout_marginTop = 6;
			
			// aapt resource value: 3
			public const int ConstraintSet_android_layout_width = 3;
			
			// aapt resource value: 0
			public const int ConstraintSet_android_orientation = 0;
			
			// aapt resource value: 16
			public const int ConstraintSet_android_rotationX = 16;
			
			// aapt resource value: 17
			public const int ConstraintSet_android_rotationY = 17;
			
			// aapt resource value: 14
			public const int ConstraintSet_android_scaleX = 14;
			
			// aapt resource value: 15
			public const int ConstraintSet_android_scaleY = 15;
			
			// aapt resource value: 10
			public const int ConstraintSet_android_transformPivotX = 10;
			
			// aapt resource value: 11
			public const int ConstraintSet_android_transformPivotY = 11;
			
			// aapt resource value: 12
			public const int ConstraintSet_android_translationX = 12;
			
			// aapt resource value: 13
			public const int ConstraintSet_android_translationY = 13;
			
			// aapt resource value: 20
			public const int ConstraintSet_android_translationZ = 20;
			
			// aapt resource value: 2
			public const int ConstraintSet_android_visibility = 2;
			
			// aapt resource value: 22
			public const int ConstraintSet_layout_constraintBaseline_creator = 22;
			
			// aapt resource value: 23
			public const int ConstraintSet_layout_constraintBaseline_toBaselineOf = 23;
			
			// aapt resource value: 24
			public const int ConstraintSet_layout_constraintBottom_creator = 24;
			
			// aapt resource value: 25
			public const int ConstraintSet_layout_constraintBottom_toBottomOf = 25;
			
			// aapt resource value: 26
			public const int ConstraintSet_layout_constraintBottom_toTopOf = 26;
			
			// aapt resource value: 27
			public const int ConstraintSet_layout_constraintDimensionRatio = 27;
			
			// aapt resource value: 28
			public const int ConstraintSet_layout_constraintEnd_toEndOf = 28;
			
			// aapt resource value: 29
			public const int ConstraintSet_layout_constraintEnd_toStartOf = 29;
			
			// aapt resource value: 30
			public const int ConstraintSet_layout_constraintGuide_begin = 30;
			
			// aapt resource value: 31
			public const int ConstraintSet_layout_constraintGuide_end = 31;
			
			// aapt resource value: 32
			public const int ConstraintSet_layout_constraintGuide_percent = 32;
			
			// aapt resource value: 33
			public const int ConstraintSet_layout_constraintHeight_default = 33;
			
			// aapt resource value: 34
			public const int ConstraintSet_layout_constraintHeight_max = 34;
			
			// aapt resource value: 35
			public const int ConstraintSet_layout_constraintHeight_min = 35;
			
			// aapt resource value: 36
			public const int ConstraintSet_layout_constraintHorizontal_bias = 36;
			
			// aapt resource value: 37
			public const int ConstraintSet_layout_constraintHorizontal_chainStyle = 37;
			
			// aapt resource value: 38
			public const int ConstraintSet_layout_constraintHorizontal_weight = 38;
			
			// aapt resource value: 39
			public const int ConstraintSet_layout_constraintLeft_creator = 39;
			
			// aapt resource value: 40
			public const int ConstraintSet_layout_constraintLeft_toLeftOf = 40;
			
			// aapt resource value: 41
			public const int ConstraintSet_layout_constraintLeft_toRightOf = 41;
			
			// aapt resource value: 42
			public const int ConstraintSet_layout_constraintRight_creator = 42;
			
			// aapt resource value: 43
			public const int ConstraintSet_layout_constraintRight_toLeftOf = 43;
			
			// aapt resource value: 44
			public const int ConstraintSet_layout_constraintRight_toRightOf = 44;
			
			// aapt resource value: 45
			public const int ConstraintSet_layout_constraintStart_toEndOf = 45;
			
			// aapt resource value: 46
			public const int ConstraintSet_layout_constraintStart_toStartOf = 46;
			
			// aapt resource value: 47
			public const int ConstraintSet_layout_constraintTop_creator = 47;
			
			// aapt resource value: 48
			public const int ConstraintSet_layout_constraintTop_toBottomOf = 48;
			
			// aapt resource value: 49
			public const int ConstraintSet_layout_constraintTop_toTopOf = 49;
			
			// aapt resource value: 50
			public const int ConstraintSet_layout_constraintVertical_bias = 50;
			
			// aapt resource value: 51
			public const int ConstraintSet_layout_constraintVertical_chainStyle = 51;
			
			// aapt resource value: 52
			public const int ConstraintSet_layout_constraintVertical_weight = 52;
			
			// aapt resource value: 53
			public const int ConstraintSet_layout_constraintWidth_default = 53;
			
			// aapt resource value: 54
			public const int ConstraintSet_layout_constraintWidth_max = 54;
			
			// aapt resource value: 55
			public const int ConstraintSet_layout_constraintWidth_min = 55;
			
			// aapt resource value: 56
			public const int ConstraintSet_layout_editor_absoluteX = 56;
			
			// aapt resource value: 57
			public const int ConstraintSet_layout_editor_absoluteY = 57;
			
			// aapt resource value: 58
			public const int ConstraintSet_layout_goneMarginBottom = 58;
			
			// aapt resource value: 59
			public const int ConstraintSet_layout_goneMarginEnd = 59;
			
			// aapt resource value: 60
			public const int ConstraintSet_layout_goneMarginLeft = 60;
			
			// aapt resource value: 61
			public const int ConstraintSet_layout_goneMarginRight = 61;
			
			// aapt resource value: 62
			public const int ConstraintSet_layout_goneMarginStart = 62;
			
			// aapt resource value: 63
			public const int ConstraintSet_layout_goneMarginTop = 63;
			
			public static int[] FontFamily = new int[] {
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130772027,
					2130772028,
					2130772029};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			public static int[] LinearConstraintLayout = new int[] {
					16842948};
			
			// aapt resource value: 0
			public const int LinearConstraintLayout_android_orientation = 0;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 6
			public const int RecyclerView_fastScrollEnabled = 6;
			
			// aapt resource value: 9
			public const int RecyclerView_fastScrollHorizontalThumbDrawable = 9;
			
			// aapt resource value: 10
			public const int RecyclerView_fastScrollHorizontalTrackDrawable = 10;
			
			// aapt resource value: 7
			public const int RecyclerView_fastScrollVerticalThumbDrawable = 7;
			
			// aapt resource value: 8
			public const int RecyclerView_fastScrollVerticalTrackDrawable = 8;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
